---
# This

- name: pagespeed | Create temporary directory
  shell: mktemp -d
  register: tempdir
  become: yes
  tags: pagespeed_setup

- name: pagespeed | Download pagespeed
  get_url:
    url="{{pagespeed_url}}"
    dest="{{ pagespeed_dir_tmp }}/"
  register: pagespeed_download
  tags: pagespeed_setup
  become: yes

- name: pagespeed | Add package
  apt: deb={{ pagespeed_dir_tmp }}/{{ pagespeed_package_deb }}
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and pagespeed_download.changed
  tags: pagespeed_setup
  become: yes

#- name: pagespeed | Install package
#  action: command apt-get -f install
#  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#  tags: pagespeed_setup

- name: pagespeed | Cleanup temporary directory
  file: name={{ tempdir.stdout }} state=absent
  tags: pagespeed_setup
  changed_when: false    
  ignore_errors: "{{ ansible_check_mode }}"    
  become: yes

- debug: msg=" pagespeed | See statisctics at http://localhost/pagespeed_console"

- name: pagespeed | Import Google GPG key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
